services:
  - type: web_service
    name: farmchainx-backend
    env: node
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
